-- C Code Lab: questions seed (generated from seed_syllabus_questions + question_content)
-- Dialect: SQLite + PostgreSQL (no vendor-specific PRAGMA).
-- Clears attempts first (FK to questions), then questions, then inserts fresh rows.

BEGIN;
DELETE FROM attempts;
DELETE FROM questions;

INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 1: Print Hello World', 'Solve a phase 1 — foundation coding task focused on ''Introduction to C''.
Problem style: Print Hello World. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'No input.', 'Print exactly: Hello World', 'This program runs without waiting for typed input.', '', 'Hello World', '[{"input": "", "output": "Hello World"}, {"input": "", "output": "Hello World"}]', '[{"input": "", "output": "Hello World"}]', 15, 'There is nothing to calculate; emit the exact required text once.', '`printf()` only may be enough. Optional: wrap in `int main()` and return 0.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 2: Print name and city', 'Solve a phase 1 — foundation coding task focused on ''Structure of a C Program''.
Problem style: Print name and city. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'Line 1: name. Line 2: city.', 'Print name on line 1, city on line 2.', 'You get two answers the user typed: first the name word, second the city word — each alone on its line.', 'Riya
Chennai', 'Riya
Chennai', '[{"input": "Ada\nBoston", "output": "Ada\nBoston"}, {"input": "Riya\nChennai", "output": "Riya\nChennai"}]', '[{"input": "Ada\nBoston", "output": "Ada\nBoston"}, {"input": "Riya\nChennai", "output": "Riya\nChennai"}, {"input": "Zoe\nParis", "output": "Zoe\nParis"}]', 15, 'Read line 1, read line 2, print exactly the same order on two separate lines.', 'Two `%s` reads with `scanf` or two narrow `fgets` strips newline; exactly two `printf` lines.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 3: Add two numbers', 'Solve a phase 1 — foundation coding task focused on ''Keywords and Identifiers''.
Problem style: Add two numbers. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'Two integers a and b.', 'Print a + b.', 'The user enters two ordinary integers.', '7 3', '10', '[{"input": "7 3", "output": "10"}, {"input": "-2 5", "output": "3"}]', '[{"input": "2 2", "output": "4"}, {"input": "10 5", "output": "15"}, {"input": "-3 -4", "output": "-7"}]', 15, 'Read two values, compute their sum, print that integer.', '`scanf` with `%d` twice or once with two `%d`; `printf` to print sum.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 4: Swap without third variable', 'Solve a phase 1 — foundation coding task focused on ''Variables''.
Problem style: Swap without third variable. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'Two integers a and b.', 'Print swapped values: b a.', 'Two integers arrive in order.', '7 3', '3 7', '[{"input": "7 3", "output": "3 7"}, {"input": "10 -1", "output": "-1 10"}]', '[{"input": "1 2", "output": "2 1"}, {"input": "9 9", "output": "9 9"}, {"input": "-5 8", "output": "8 -5"}]', 15, 'Rewrite their positions so first printed value equals second input (use a temporary or arithmetic trick).', 'Three variables or bitwise/arithmetic swap; use `scanf` / `printf`.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 5: Read name and age greeting', 'Solve a phase 1 — foundation coding task focused on ''Data Types''.
Problem style: Read name and age greeting. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'Line 1: name string. Line 2: integer age.', 'Print one greeting sentence exactly.', 'Person gives one word nickname, then a normal human age.', 'Alex
21', 'Hello Alex, you are 21 years old.', '[{"input": "Mia\n19", "output": "Hello Mia, you are 19 years old."}, {"input": "Alex\n21", "output": "Hello Alex, you are 21 years old."}]', '[{"input": "Amy\n17", "output": "Hello Amy, you are 17 years old."}, {"input": "Leo\n0", "output": "Hello Leo, you are 0 years old."}, {"input": "Zoe\n100", "output": "Hello Zoe, you are 100 years old."}]', 15, 'Build one sentence literally like: Hello <name>, you are <age> years old.', '`char name[]`; `scanf("%s%d", …)` plus `printf`; mind comma placement.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 6: Read character ASCII', 'Solve a phase 1 — foundation coding task focused on ''Constants''.
Problem style: Read character ASCII. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'A single character on one line.', 'Print its decimal ASCII code.', 'One visible character keyed by user.', 'A', '65', '[{"input": "A", "output": "65"}, {"input": "z", "output": "122"}]', '[{"input": "0", "output": "48"}, {"input": "9", "output": "57"}, {"input": "@", "output": "64"}]', 15, 'Cast or print integer form of signed/unsigned char semantics.', '`getchar()` / `scanf(" %c", &ch)`; cast `(int)`; `%d`.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 7: Read float decimal places', 'Solve a phase 1 — foundation coding task focused on ''Header Files''.
Problem style: Read float decimal places. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'One float on one line.', 'Print three values with 2, 4, then 6 decimal places, space-separated.', 'One fractional number shown with decimal digits.', '3.14159', '3.14 3.1416 3.141590', '[{"input": "12.345678", "output": "12.35 12.3457 12.345678"}, {"input": "3.14159", "output": "3.14 3.1416 3.141590"}]', '[{"input": "9.87", "output": "9.87 9.8700 9.870000"}, {"input": "0.1", "output": "0.10 0.1000 0.100000"}, {"input": "2.5", "output": "2.50 2.5000 2.500000"}]', 15, 'Format same numeric value thrice widths 2 then 4 then 6 after decimal.', '`printf` width/precision modifiers or `sprintf`/`snprintf`; read `double` `%lf`.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 8: Print data type sizes lab', 'Solve a phase 1 — foundation coding task focused on ''Input and Output (printf, scanf)''.
Problem style: Print data type sizes lab. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'No input.', 'Print four integers separated by spaces: sizeof(int) sizeof(float) sizeof(double) sizeof(unsigned char).', 'No input values (lab assumes fixed widths for grading).', '', '4 4 8 1', '[{"input": "", "output": "4 4 8 1"}]', '[{"input": "", "output": "4 4 8 1"}]', 15, 'Emit four ints matching sizeof rules described in lectures.', '`sizeof(int)` typed printout; spaced integers.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 9: Print simple box border', 'Solve a phase 1 — foundation coding task focused on ''Compilation process''.
Problem style: Print simple box border. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'One integer n (side length of hollow square drawn with ''*''). Middle uses spaces.', 'Print exactly n rows: rows 1 and n are n stars; rows 2..n-1 are star, (n-2 spaces), star.', 'Border size decides rows/columns counts for hollow square artwork.', '3', '***
* *
***', '[{"input": "3", "output": "***\n* *\n***"}, {"input": "4", "output": "****\n*  *\n*  *\n****"}]', '[{"input": "3", "output": "***\n* *\n***"}, {"input": "4", "output": "****\n*  *\n*  *\n****"}, {"input": "5", "output": "*****\n*   *\n*   *\n*   *\n*****"}]', 15, 'First/last rows all stars; middle rows stars with interior spaces.', 'Double loop; `%c` repeats or stitched `printf` each row newline.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 1 — Foundation Practice 10: Student record variables', 'Solve a phase 1 — foundation coding task focused on ''Introduction to C''.
Problem style: Student record variables. Read input from stdin and print exact output.', 'Phase 1 — Foundation', 'medium', 'Four lines: name, age, grade letter, tuition fees.', 'Print four fields separated by spaces: name age grade fees.', 'Four separate answers: word name, numeric age, one letter grade, tuition digits.', 'Mia
19
B
72000', 'Mia 19 B 72000', '[{"input": "Ada\n21\nA\n90000", "output": "Ada 21 A 90000"}, {"input": "Mia\n19\nB\n72000", "output": "Mia 19 B 72000"}]', '[{"input": "Raj\n22\nC\n61000", "output": "Raj 22 C 61000"}, {"input": "Zoe\n18\nF\n8000", "output": "Zoe 18 F 8000"}, {"input": "Leo\n30\nD\n41234", "output": "Leo 30 D 41234"}]', 15, 'Read four lines in order — echo them spaced on one formatted output line.', 'Mix `%s` `%d` `%c`; watch whitespace newline handling.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 1: Check even/odd', 'Solve a phase 2 — logic building & flow control coding task focused on ''Arithmetic, Relational, Logical, Assignment''.
Problem style: Check even/odd. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'One integer n.', 'Print Even if n is even, else Odd.', 'One integer (can be negative or zero).', '8', 'Even', '[{"input": "8", "output": "Even"}, {"input": "7", "output": "Odd"}]', '[{"input": "0", "output": "Even"}, {"input": "-3", "output": "Odd"}, {"input": "14", "output": "Even"}]', 15, 'If remainder modulo 2 is 0 → Even; else → Odd.', 'Modulus `%`; `scanf` `%d`; `printf` literal words Even / Odd.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 2: Find largest of 3 numbers', 'Solve a phase 2 — logic building & flow control coding task focused on ''Increment and Decrement operators''.
Problem style: Find largest of 3 numbers. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'Three integers a, b, c.', 'Print the largest value.', 'Three integers separated on one line (or consecutive reads).', '9 2 5', '9', '[{"input": "9 2 5", "output": "9"}, {"input": "-1 -3 -2", "output": "-1"}]', '[{"input": "1 2 3", "output": "3"}, {"input": "5 5 1", "output": "5"}, {"input": "7 4 7", "output": "7"}]', 15, 'Compare pairwise (nested if–else or a small chain); keep the greatest.', '`if`/`else`; optional `scanf` three `%d`; one `printf` for winner.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 3: Grade calculator', 'Solve a phase 2 — logic building & flow control coding task focused on ''Conditional Statements (if, else, switch)''.
Problem style: Grade calculator. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'One integer marks.', 'Print grade: A (>=90), B (>=80), C (>=70), D (>=60), F (<60).', 'One mark from 0 to 100.', '82', 'B', '[{"input": "82", "output": "B"}, {"input": "95", "output": "A"}]', '[{"input": "74", "output": "C"}, {"input": "60", "output": "D"}, {"input": "48", "output": "F"}]', 15, 'Map ranges to letter grades A,B,C,D,F with clear cut-offs.', '`if`-`else if` ladder or concise comparisons; `%d`; print single letter.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 4: Day of week switch', 'Solve a phase 2 — logic building & flow control coding task focused on ''Loops (for, while, do-while)''.
Problem style: Day of week switch. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'One integer.', 'Print abbreviated weekday exactly: Mon Tue Wed Thu Fri Sat Sun', 'Integer 1..7 referencing weekday numbering from handout.', '3', 'Wed', '[{"input": "1", "output": "Mon"}, {"input": "7", "output": "Sun"}]', '[{"input": "4", "output": "Thu"}, {"input": "6", "output": "Sat"}, {"input": "2", "output": "Tue"}]', 15, '`switch`/cases map day index to abbreviated label.', '`switch`; `scanf` `%d`; `printf` abbreviated names.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 5: Calculator switch menu', 'Solve a phase 2 — logic building & flow control coding task focused on ''Jump statements (break, continue, goto)''.
Problem style: Calculator switch menu. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'Line 1: op. Line 2: a. Line 3: b. Integer division for ''/''.', 'Print integer result.', 'Operator letter then two operands lines.', '+
4
11', '15', '[{"input": "-\n50\n38", "output": "12"}, {"input": "*\n3\n11", "output": "33"}]', '[{"input": "+\n10\n5", "output": "15"}, {"input": "/\n49\n7", "output": "7"}, {"input": "*\n6\n7", "output": "42"}]', 15, '`switch(operator)` computes + − * /. Integer-divide semantics as stated.', '`%c`; optional space skip; `%d` pairs; beware newline before char read.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 6: Print multiplication table', 'Solve a phase 2 — logic building & flow control coding task focused on ''Arithmetic, Relational, Logical, Assignment''.
Problem style: Print multiplication table. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'One integer n.', 'Print first 10 multiples of n separated by spaces.', 'One positive integer controlling the factor.', '5', '5 10 15 20 25 30 35 40 45 50', '[{"input": "5", "output": "5 10 15 20 25 30 35 40 45 50"}, {"input": "2", "output": "2 4 6 8 10 12 14 16 18 20"}]', '[{"input": "1", "output": "1 2 3 4 5 6 7 8 9 10"}, {"input": "7", "output": "7 14 21 28 35 42 49 56 63 70"}, {"input": "3", "output": "3 6 9 12 15 18 21 24 27 30"}]', 15, 'Print first ten multiples separated by spaces (loop with counter).', '`for` loop; `printf` with space between numbers.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 7: Read until zero sum', 'Solve a phase 2 — logic building & flow control coding task focused on ''Increment and Decrement operators''.
Problem style: Read until zero sum. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'One integer per line; last line is 0 to stop reading.', 'Print sum of all integers before the line containing 0.', 'User enters positive steps line-by-line stopping at sentinel line reading zero.', '2
12
18
20
0', '52', '[{"input": "5\n30\n50\n55\n0", "output": "140"}, {"input": "2\n12\n18\n20\n0", "output": "52"}]', '[{"input": "1\n7\n9\n17\n0", "output": "17"}, {"input": "3\n0", "output": "3"}, {"input": "10\n20\n5\n0", "output": "35"}]', 15, 'Accumulate totals until encountering exactly zero sentinel line exiting loop.', '`while` reading `%d`; break or condition with sum accumulator.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 8: Prime check', 'Solve a phase 2 — logic building & flow control coding task focused on ''Conditional Statements (if, else, switch)''.
Problem style: Prime check. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'One integer n.', 'Print Prime or Not', 'One integer roughly ≥2 check primality semantics.', '7', 'Prime', '[{"input": "8", "output": "Not"}, {"input": "7", "output": "Prime"}]', '[{"input": "2", "output": "Prime"}, {"input": "9", "output": "Not"}, {"input": "17", "output": "Prime"}]', 15, 'Test divisibility by integers upto sqrt heuristic or trial division.', '`for` divides; modulus tests; literals Prime / Not output.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 9: Leap year', 'Solve a phase 2 — logic building & flow control coding task focused on ''Loops (for, while, do-while)''.
Problem style: Leap year. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'One integer year.', 'Print Leap or Not', 'One calendar year typed.', '2024', 'Leap', '[{"input": "2023", "output": "Not"}, {"input": "2024", "output": "Leap"}]', '[{"input": "2000", "output": "Leap"}, {"input": "1900", "output": "Not"}, {"input": "1996", "output": "Leap"}]', 15, 'Divisibility by 400 /100 /4 Gregorian rules condensed.', '`if` ladders; Booleans combos; Leap / Not strings.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 2 — Logic Building & Flow Control Practice 10: Simple interest', 'Solve a phase 2 — logic building & flow control coding task focused on ''Jump statements (break, continue, goto)''.
Problem style: Simple interest. Read input from stdin and print exact output.', 'Phase 2 — Logic Building & Flow Control', 'medium', 'Three lines: principal P, rate R, time T (all integers).', 'Print simple interest as integer.', 'Three integers Principal Rate Time whole numbers.', '1000
5
2', '100', '[{"input": "2000\n4\n3", "output": "240"}, {"input": "1000\n5\n2", "output": "100"}]', '[{"input": "500\n10\n1", "output": "50"}, {"input": "1500\n8\n2", "output": "240"}, {"input": "9000\n0\n5", "output": "0"}]', 15, '`SI = Principal*Rate*Time/100` integer division semantics per spec.', '`long long` if wide multiplies avoiding overflow.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 1: Print primes in range', 'Solve a phase 3 — functions coding task focused on ''Function declaration, definition, and call''.
Problem style: Print primes in range. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'Two integers lo hi on one line.', 'Print all primes in [lo, hi] inclusive, space-separated, ascending.', 'Two bounds inclusive lo hi moderate span.', '5
15', '5 7 11 13', '[{"input": "1\n10", "output": "2 3 5 7"}, {"input": "5\n15", "output": "5 7 11 13"}]', '[{"input": "2\n2", "output": "2"}, {"input": "14\n18", "output": "17"}, {"input": "20\n30", "output": "23 29"}]', 15, 'Double loop or sieve-like walk printing ascending primes spaced.', '`is_prime` helper function recommended; `%d spaced`.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 2: Armstrong number check', 'Solve a phase 3 — functions coding task focused on ''Call by value and call by reference''.
Problem style: Armstrong number check. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'One integer n.', 'Print Yes or No if n is an Armstrong number.', 'One integer verifying digit-power property.', '153', 'Yes', '[{"input": "9474", "output": "Yes"}, {"input": "123", "output": "No"}]', '[{"input": "1", "output": "Yes"}, {"input": "370", "output": "Yes"}, {"input": "200", "output": "No"}]', 15, 'Count digits duplicate value split digits powering sums compare original.', '`while digit extract`; `pow`/manual multiply loop; Yes/No print.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 3: Floyd triangle pattern', 'Solve a phase 3 — functions coding task focused on ''Using functions for primes, powers, factorial, gcd, lcm''.
Problem style: Floyd triangle pattern. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'One integer n (number of rows).', 'Floyd triangle: row i has i numbers, space-separated; rows separated by newline.', 'Height rows grows consecutive integers pattern.', '3', '1
2 3
4 5 6', '[{"input": "2", "output": "1\n2 3"}, {"input": "3", "output": "1\n2 3\n4 5 6"}]', '[{"input": "1", "output": "1"}, {"input": "4", "output": "1\n2 3\n4 5 6\n7 8 9 10"}, {"input": "3", "output": "1\n2 3\n4 5 6"}]', 15, '`counter++` increments each printed cell nesting row column loops.', 'Nested loops; spaces between ints same row newline between rows.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 4: Equilateral star pattern', 'Solve a phase 3 — functions coding task focused on ''Function declaration, definition, and call''.
Problem style: Equilateral star pattern. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'One integer n (rows of centered star triangle).', 'Each row has leading spaces then stars separated by single space; pattern as sample.', 'Row count pyramid pattern.', '4', '   *
  * *
 * * *
* * * *', '[{"input": "2", "output": " *\n* *"}, {"input": "4", "output": "   *\n  * *\n * * *\n* * * *"}]', '[{"input": "1", "output": "*"}, {"input": "3", "output": "  *\n * *\n* * *"}, {"input": "4", "output": "   *\n  * *\n * * *\n* * * *"}]', 15, 'Per row prepend spaces trail spaced stars mirroring symmetrical triangle illustration.', '`for` indentation spaces inner star printing.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 5: Break on negative sum', 'Solve a phase 3 — functions coding task focused on ''Call by value and call by reference''.
Problem style: Break on negative sum. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'First line count n, then n integers one per line (last may be negative).', 'Print sum of values before first negative integer.', 'Count prefixed then sequence entries until negative sentinel occurs.', '3
5
8
-2', '13', '[{"input": "2\n10\n-1", "output": "10"}, {"input": "3\n5\n8\n-2", "output": "13"}]', '[{"input": "4\n1\n2\n3\n-9", "output": "6"}, {"input": "1\n-5", "output": "0"}, {"input": "5\n2\n2\n2\n2\n-1", "output": "8"}]', 15, 'Add positives strictly before first negative skipping negative itself.', '`for`/`while`; break semantics; tally.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 6: isEven function loop', 'Solve a phase 3 — functions coding task focused on ''Using functions for primes, powers, factorial, gcd, lcm''.
Problem style: isEven function loop. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'One integer n.', 'Print all even numbers from 2 to n inclusive, space-separated.', 'Upper bound counting evens inclusively downward.', '10', '2 4 6 8 10', '[{"input": "6", "output": "2 4 6"}, {"input": "10", "output": "2 4 6 8 10"}]', '[{"input": "1", "output": ""}, {"input": "4", "output": "2 4"}, {"input": "12", "output": "2 4 6 8 10 12"}]', 15, '`if (!(i%2))` collect even sequence from 2..n spaced.', 'Helper `unsigned isEven_like` conceptual or inline check.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 7: gcd euclidean', 'Solve a phase 3 — functions coding task focused on ''Function declaration, definition, and call''.
Problem style: gcd euclidean. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'Two integers a b on separate lines.', 'Print GCD(a,b).', 'Two positive ints.', '48
18', '6', '[{"input": "100\n35", "output": "5"}, {"input": "48\n18", "output": "6"}]', '[{"input": "7\n13", "output": "1"}, {"input": "54\n24", "output": "6"}, {"input": "17\n17", "output": "17"}]', 15, '`while(b){ r=a%b;a=b;b=r;} ` classic swap.', '`%` loop; iterative not necessarily recursion.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 8: lcm using gcd', 'Solve a phase 3 — functions coding task focused on ''Call by value and call by reference''.
Problem style: lcm using gcd. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'Two integers a b on separate lines.', 'Print LCM(a,b) using LCM = a*b/GCD(a,b) with integer arithmetic.', 'Two ints product moderate.', '4
6', '12', '[{"input": "5\n7", "output": "35"}, {"input": "4\n6", "output": "12"}]', '[{"input": "3\n9", "output": "9"}, {"input": "8\n12", "output": "24"}, {"input": "11\n13", "output": "143"}]', 15, '`LCM=a*b/GCD(a,b)` after computing gcd reliably.', '`long long`; divide after multiply carefully ordering.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 9: Recursive factorial', 'Solve a phase 3 — functions coding task focused on ''Using functions for primes, powers, factorial, gcd, lcm''.
Problem style: Recursive factorial. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'One integer n.', 'Print n!.', 'Small non-negative integer n (factorial grows fast).', '5', '120', '[{"input": "5", "output": "120"}, {"input": "0", "output": "1"}]', '[{"input": "1", "output": "1"}, {"input": "6", "output": "720"}, {"input": "3", "output": "6"}]', 15, 'Multiply 1 × 2 × … × n.', '`for` or `while`; start from 1; use `long long` if needed.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 3 — Functions Practice 10: Fibonacci series', 'Solve a phase 3 — functions coding task focused on ''Function declaration, definition, and call''.
Problem style: Fibonacci series. Read input from stdin and print exact output.', 'Phase 3 — Functions', 'medium', 'One integer n (number of terms).', 'Print first n Fibonacci numbers separated by spaces.', 'Count of terms to emit.', '7', '0 1 1 2 3 5 8', '[{"input": "5", "output": "0 1 1 2 3"}, {"input": "1", "output": "0"}]', '[{"input": "2", "output": "0 1"}, {"input": "3", "output": "0 1 1"}, {"input": "6", "output": "0 1 1 2 3 5"}]', 15, 'Start 0 and 1 (or variants per statement); derive next iteratively.', '`for`; two variables swapping previous terms; spaced `printf`.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 1: Array reverse print', 'Solve a phase 4 — data collections coding task focused on ''One-dimensional arrays''.
Problem style: Array reverse print. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'First line n, second line n integers.', 'Print elements in reverse order, space-separated.', '`n` then list length n ints.', '4
1 2 3 4', '4 3 2 1', '[{"input": "3\n9 8 7", "output": "7 8 9"}, {"input": "4\n1 2 3 4", "output": "4 3 2 1"}]', '[{"input": "1\n42", "output": "42"}, {"input": "2\n0 5", "output": "5 0"}, {"input": "5\n1 1 2 3 5", "output": "5 3 2 1 1"}]', 15, 'Index from last-to-first printing sequentially.', '`for (i=n-1; i>=0; i--)` and array storage.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 2: Max min average array', 'Solve a phase 4 — data collections coding task focused on ''Two-dimensional arrays (matrices)''.
Problem style: Max min average array. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'First line n, second line n integers.', 'Print max min average as integers: average = floor(sum/n).', '`n` then n ints manageable array sizes.', '4
2 8 4 6', '8 2 5', '[{"input": "3\n10 20 30", "output": "30 10 20"}, {"input": "4\n2 8 4 6", "output": "8 2 5"}]', '[{"input": "1\n7", "output": "7 7 7"}, {"input": "2\n1 2", "output": "2 1 1"}, {"input": "5\n1 1 1 1 1", "output": "1 1 1"}]', 15, 'One pass trackers min/max and sum aggregator floor average.', '`/` integer division nuances; spaced triple print.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 3: Second largest array', 'Solve a phase 4 — data collections coding task focused on ''Strings basics and manipulation''.
Problem style: Second largest array. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'First line n, second line n integers.', 'Print the largest value that is strictly less than the global maximum (ignore duplicate copies of the maximum).', 'At least length two ints general distinct semantics allowed duplicates.', '5
3 9 9 1 4', '4', '[{"input": "3\n5 5 3", "output": "3"}, {"input": "5\n3 9 9 1 4", "output": "4"}]', '[{"input": "2\n1 2", "output": "1"}, {"input": "4\n4 4 4 4", "output": "4"}, {"input": "6\n10 20 8 15 9 22", "output": "20"}, {"input": "3\n100 75 90", "output": "90"}, {"input": "4\n-2 -10 -10 -100", "output": "-10"}]', 15, 'First find max peel second maximal strictly less-than-max semantics per problem.', '`if` interplay two-pass scan recommended.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 4: Linear search array', 'Solve a phase 4 — data collections coding task focused on ''One-dimensional arrays''.
Problem style: Linear search array. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'Line 1: n. Line 2: n integers. Line 3: target.', 'Print 0-based index of first occurrence, or -1 if not found.', 'Array listing plus target finder.', '5
1 4 7 9 2
7', '2', '[{"input": "3\n5 5 3\n5", "output": "0"}, {"input": "5\n1 4 7 9 2\n7", "output": "2"}]', '[{"input": "4\n8 8 8 8\n8", "output": "0"}, {"input": "2\n1 2\n3", "output": "-1"}, {"input": "1\n42\n42", "output": "0"}]', 15, 'Linear scan earliest index equality else −1 sentinel.', '`for i` compare `arr[i]`; integer index print `-1 absent`.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 5: Matrix print 3x3', 'Solve a phase 4 — data collections coding task focused on ''Two-dimensional arrays (matrices)''.
Problem style: Matrix print 3x3. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'Three lines, each with three integers.', 'Print matrix row-wise with spaces between numbers per row.', 'Exactly nine ints row major three lines typed.', '1 2 3
4 5 6
7 8 9', '1 2 3
4 5 6
7 8 9', '[{"input": "0 0 0\n1 1 1\n2 2 2", "output": "0 0 0\n1 1 1\n2 2 2"}]', '[{"input": "9 8 7\n6 5 4\n3 2 1", "output": "9 8 7\n6 5 4\n3 2 1"}, {"input": "1 0 0\n0 1 0\n0 0 1", "output": "1 0 0\n0 1 0\n0 0 1"}]', 15, 'Mirror reading row ordering printing mirrored layout.', '`int m[3][3]` loops row col.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 6: Matrix row column sums', 'Solve a phase 4 — data collections coding task focused on ''Strings basics and manipulation''.
Problem style: Matrix row column sums. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'Three lines, each three integers.', 'Line 1: row sums space-separated. Line 2: column sums space-separated.', '`3 × 3` numeric grid unchanged.', '1 2 3
4 5 6
7 8 9', '6 15 24
12 15 18', '[{"input": "1 1 1\n1 1 1\n1 1 1", "output": "3 3 3\n3 3 3"}]', '[{"input": "1 2 3\n4 5 6\n7 8 9", "output": "6 15 24\n12 15 18"}, {"input": "0 0 1\n0 1 0\n1 0 0", "output": "1 1 1\n1 1 1"}]', 15, 'Row sums scanning columns; transpose-like column accumulators separately.', '`for` nesting plus secondary accumulators lines.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 7: Matrix addition 3x3', 'Solve a phase 4 — data collections coding task focused on ''One-dimensional arrays''.
Problem style: Matrix addition 3x3. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'r c, then matrix A (r lines), then matrix B (r lines).', 'Print A+B matrix row-wise.', 'Dimensions plus two matrices stacked in stdin order.', '2 2
1 2
3 4
5 6
7 8', '6 8
10 12', '[{"input": "1 2\n1 3\n4 5", "output": "5 8"}, {"input": "2 1\n2\n3\n1\n4", "output": "3\n7"}]', '[{"input": "1 1\n2\n7", "output": "9"}, {"input": "2 2\n1 1\n1 1\n2 2\n2 2", "output": "3 3\n3 3"}, {"input": "1 3\n1 2 3\n3 2 1", "output": "4 4 4"}]', 15, 'For each row/column index, add matching cells.', 'Nested loops; 2-D arrays `[r][c]`; store then print.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 8: Matrix transpose', 'Solve a phase 4 — data collections coding task focused on ''Two-dimensional arrays (matrices)''.
Problem style: Matrix transpose. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'Three lines, each three integers.', 'Print transpose (3 lines).', '`3 × 3` square matrix.', '1 2 3
4 5 6
7 8 9', '1 4 7
2 5 8
3 6 9', '[{"input": "1 0 0\n0 1 0\n0 0 1", "output": "1 0 0\n0 1 0\n0 0 1"}]', '[{"input": "1 2 3\n0 0 0\n7 8 9", "output": "1 0 7\n2 0 8\n3 0 9"}, {"input": "1 2 3\n4 5 6\n7 8 9", "output": "1 4 7\n2 5 8\n3 6 9"}, {"input": "2 0 1\n0 3 0\n1 0 2", "output": "2 0 1\n0 3 0\n1 0 2"}]', 15, '`out[j][i]=in[i][j]` mapping.', '`i j` swaps indexes printing three lines.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 9: Symmetric matrix check', 'Solve a phase 4 — data collections coding task focused on ''Strings basics and manipulation''.
Problem style: Symmetric matrix check. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'Three lines, each three integers.', 'Print Yes if symmetric (A[i][j]==A[j][i]), else No.', '`3 × 3` ints.', '1 2 3
2 4 5
3 5 6', 'Yes', '[{"input": "1 0 0\n0 1 0\n0 0 1", "output": "Yes"}]', '[{"input": "1 0 0\n0 1 0\n0 0 1", "output": "Yes"}, {"input": "1 2 3\n0 1 4\n5 6 0", "output": "No"}, {"input": "1 2 3\n2 4 5\n3 5 6", "output": "Yes"}]', 15, '`A[i][j]==A[j][i]` all ordered pairs symmetrical property.', '`for` doubly nested comparators booleans degrade Yes/No quick.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 4 — Data Collections Practice 10: Count above average', 'Solve a phase 4 — data collections coding task focused on ''One-dimensional arrays''.
Problem style: Count above average. Read input from stdin and print exact output.', 'Phase 4 — Data Collections', 'medium', 'Line 1: n. Line 2: n integers.', 'Count elements strictly greater than floor(average); average = floor(sum/n).', 'Array ints general distribution.', '5
2 2 2 2 8', '1', '[{"input": "4\n1 2 3 4", "output": "2"}, {"input": "5\n2 2 2 2 8", "output": "1"}]', '[{"input": "3\n10 10 10", "output": "0"}, {"input": "4\n9 10 11 100", "output": "1"}, {"input": "2\n5 15", "output": "1"}]', 15, '`avg=floor(sum/n)` tally strictly exceeding threshold.', '`sum` accumulating two-pass or store array then second pass tally.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 1: Pascal triangle rows', 'Solve a phase 5 — problem practice coding task focused on ''Mixed array, matrix, string, and number-theory drills''.
Problem style: Pascal triangle rows. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'One integer n = number of rows.', 'Print Pascal triangle: row i has i integers, space-separated.', '`n` rows modest combinator growth.', '3', '1
1 1
1 2 1', '[{"input": "4", "output": "1\n1 1\n1 2 1\n1 3 3 1"}, {"input": "3", "output": "1\n1 1\n1 2 1"}]', '[{"input": "1", "output": "1"}, {"input": "2", "output": "1\n1 1"}, {"input": "5", "output": "1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1"}]', 15, '`C(n,k)` recurrence triangular addition neighbor parents rule.', '`arr[i][j]=arr[i-1][j-1]+arr[i-1][j]` base ones edges.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 2: String length manual', 'Solve a phase 5 — problem practice coding task focused on ''Patterns, sorts, palindromes, gcd/lcm bundles''.
Problem style: String length manual. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'Single line string (ASCII).', 'Print length without using strlen.', 'Non-empty string without embedded newline simplifying scanner.', 'coding', '6', '[{"input": "hi", "output": "2"}]', '[{"input": "abcd", "output": "4"}, {"input": "race", "output": "4"}, {"input": "z", "output": "1"}]', 15, '`len=0; while(str[len]) ++len ;` iterative.', '`char[]`; forbid `strlen` verifying spec.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 3: Reverse a string', 'Solve a phase 5 — problem practice coding task focused on ''Mixed array, matrix, string, and number-theory drills''.
Problem style: Reverse a string. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'One string (no spaces).', 'Print reversed string.', 'One word/token without spaces (matching how the checker reads input).', 'hello', 'olleh', '[{"input": "hello", "output": "olleh"}, {"input": "abc", "output": "cba"}]', '[{"input": "a", "output": "a"}, {"input": "racecar", "output": "racecar"}, {"input": "coder", "output": "redoc"}]', 15, 'Walk from both ends swapping, or iterate backward building output.', '`char[]`; indexing; `%s` or `%c` loops; optionally `strlen` if allowed.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 4: Check palindrome', 'Solve a phase 5 — problem practice coding task focused on ''Patterns, sorts, palindromes, gcd/lcm bundles''.
Problem style: Check palindrome. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'One string (no spaces).', 'Print Yes if palindrome, else No.', 'One string with no gaps.', 'madam', 'Yes', '[{"input": "madam", "output": "Yes"}, {"input": "hello", "output": "No"}]', '[{"input": "a", "output": "Yes"}, {"input": "abba", "output": "Yes"}, {"input": "abc", "output": "No"}]', 15, 'Compare character at i with symmetric position n−1−i.', '`for`/`while`; `%s`; print Yes / No literals.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 5: Count vowels consonants spaces', 'Solve a phase 5 — problem practice coding task focused on ''Mixed array, matrix, string, and number-theory drills''.
Problem style: Count vowels consonants spaces. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'One line: sentence.', 'Print three integers: vowels (aeiou AEIOU), consonants (other letters), spaces.', 'One sentence letters spaces only simplifying classification.', 'Hi there', '3 4 1', '[{"input": "aeiou", "output": "5 0 0"}, {"input": "Hi there", "output": "3 4 1"}]', '[{"input": "ABC", "output": "1 2 0"}, {"input": "a b c", "output": "1 2 2"}, {"input": "rhythm", "output": "0 6 0"}]', 15, '`if vowel tally else consonant tally else space increment`.', '`isalpha`/`isspace` optional manual classification triple integers output.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 6: Concatenate without strcat', 'Solve a phase 5 — problem practice coding task focused on ''Patterns, sorts, palindromes, gcd/lcm bundles''.
Problem style: Concatenate without strcat. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'Line 1 string A; line 2 string B.', 'Print A+B exactly.', 'Two textual tokens sequentially lines.', 'code
lab', 'codelab', '[{"input": "ab\ncd", "output": "abcd"}, {"input": "hello\n!", "output": "hello!"}]', '[{"input": "x\nyz", "output": "xyz"}, {"input": "tree\nHouse", "output": "treeHouse"}, {"input": "a\nb", "output": "ab"}]', 15, '`dest[i++]=src` manual copy both segments.', '`char out[]`; cursor index append loop.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 7: Bubble sort array', 'Solve a phase 5 — problem practice coding task focused on ''Mixed array, matrix, string, and number-theory drills''.
Problem style: Bubble sort array. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'Line 1: n. Line 2: n integers.', 'Print sorted ascending, space-separated (bubble sort / any stable O(n^2) ok).', '`n` moderate sortable ints.', '4
4 1 3 2', '1 2 3 4', '[{"input": "3\n9 1 5", "output": "1 5 9"}, {"input": "4\n4 1 3 2", "output": "1 2 3 4"}]', '[{"input": "2\n2 1", "output": "1 2"}, {"input": "5\n5 4 3 2 1", "output": "1 2 3 4 5"}, {"input": "1\n7", "output": "7"}]', 15, '`n-1 passes` adjacent swap until stable sorted ascending.', 'Nested loops flag optional micro optimization unstoppable ok.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 8: Palindrome number', 'Solve a phase 5 — problem practice coding task focused on ''Patterns, sorts, palindromes, gcd/lcm bundles''.
Problem style: Palindrome number. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'One integer n (no leading zeros except single 0).', 'Print Yes if decimal digits read same forward/backward, else No.', 'Integer decimal digit symmetry checking.', '121', 'Yes', '[{"input": "123", "output": "No"}, {"input": "121", "output": "Yes"}]', '[{"input": "0", "output": "Yes"}, {"input": "1221", "output": "Yes"}, {"input": "10", "output": "No"}]', 15, '`reverse_digits` accumulator compare originals.', '`while n>0 remainder build reversed`.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 9: Strong number check', 'Solve a phase 5 — problem practice coding task focused on ''Mixed array, matrix, string, and number-theory drills''.
Problem style: Strong number check. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'One integer n.', 'Print Yes if sum of factorials of digits equals n, else No.', 'Integer moderate digit factorial property.', '145', 'Yes', '[{"input": "145", "output": "Yes"}, {"input": "123", "output": "No"}]', '[{"input": "1", "output": "Yes"}, {"input": "2", "output": "Yes"}, {"input": "146", "output": "No"}]', 15, '`digit factorial sum` reused small helper facts precompute maybe.', '`switch` factorial micro function per digit aggregator.', NULL);
INSERT INTO questions (title, description, module, difficulty, input_format, output_format, constraints, sample_input, expected_output, examples_json, test_cases_json, time_limit_minutes, algorithm_hint, functions_hint, efficient_solution) VALUES ('Phase 5 — Problem Practice Practice 10: Right angle star pattern', 'Solve a phase 5 — problem practice coding task focused on ''Patterns, sorts, palindromes, gcd/lcm bundles''.
Problem style: Right angle star pattern. Read input from stdin and print exact output.', 'Phase 5 — Problem Practice', 'medium', 'One integer n.', 'Print a right-angle star pattern with n lines.', 'One height n determines how many lines of stars.', '3', '*
**
***', '[{"input": "3", "output": "*\n**\n***"}, {"input": "1", "output": "*"}]', '[{"input": "2", "output": "*\n**"}, {"input": "4", "output": "*\n**\n***\n****"}, {"input": "5", "output": "*\n**\n***\n****\n*****"}]', 15, 'Outer loop = line; inner loop prints increasing star counts.', 'Nested loops; nested `printf` or print `*` in inner loop.', NULL);
COMMIT;

-- Total rows: 50